// <auto-generated />
using System;
using BarberiaTurnos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarberiaTurnos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310144029_AddCancelacionPendienteIds")]
    partial class AddCancelacionPendienteIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarberiaTurnos.Models.CierreCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadTurnos")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaFiltro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalRecaudado")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("CierresCaja");
                });

            modelBuilder.Entity("BarberiaTurnos.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Telefono", "Nombre")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BarberiaTurnos.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Servicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Corte Clásico",
                            Precio = 15000m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Corte Desvanecido",
                            Precio = 17000m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Corte y Barba Marcada",
                            Precio = 23000m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Corte y Barba",
                            Precio = 25000m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Corte y Cejas",
                            Precio = 20000m
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "Corte y Raya",
                            Precio = 19000m
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Nombre = "Corte y Figura",
                            Precio = 22000m
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Nombre = "Despunte de Cabello",
                            Precio = 10000m
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Nombre = "Barba",
                            Precio = 8000m
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Nombre = "Cejas con Cuchilla",
                            Precio = 5000m
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Nombre = "Cejas con Cera",
                            Precio = 10000m
                        });
                });

            modelBuilder.Entity("BarberiaTurnos.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BarberoId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DiaTurno")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicioAtencion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NivelAviso")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric");

                    b.Property<int>("TurnoDiario")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BarberoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("BarberiaTurnos.Models.TurnoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PrecioCobrado")
                        .HasColumnType("numeric");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId");

                    b.HasIndex("TurnoId");

                    b.ToTable("TurnoDetalles");
                });

            modelBuilder.Entity("BarberiaTurnos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = false,
                            Nombre = "Admin",
                            Pin = "0000",
                            Rol = "Admin"
                        });
                });

            modelBuilder.Entity("BarberiaTurnos.Models.WhatsAppState", b =>
                {
                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<int?>("BarberoIdTemporal")
                        .HasColumnType("integer");

                    b.Property<string>("CancelacionPendienteIds")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DiaTurnoTemporal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstadoActual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreTemporal")
                        .HasColumnType("text");

                    b.Property<DateTime>("UltimaInteraccion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Telefono");

                    b.ToTable("WhatsAppStates");
                });

            modelBuilder.Entity("BarberiaTurnos.Models.CierreCaja", b =>
                {
                    b.HasOne("BarberiaTurnos.Models.Usuario", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("BarberiaTurnos.Models.Turno", b =>
                {
                    b.HasOne("BarberiaTurnos.Models.Usuario", "Barbero")
                        .WithMany()
                        .HasForeignKey("BarberoId");

                    b.HasOne("BarberiaTurnos.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbero");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BarberiaTurnos.Models.TurnoDetalle", b =>
                {
                    b.HasOne("BarberiaTurnos.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberiaTurnos.Models.Turno", "Turno")
                        .WithMany("Detalles")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("BarberiaTurnos.Models.Turno", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
