// <auto-generated />
using System;
using BarberiaTurnos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarberiaTurnos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211163051_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarberiaTurnos.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Telefono")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BarberiaTurnos.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Servicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Corte Clásico",
                            Precio = 15000m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Corte Desvanecido",
                            Precio = 17000m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Corte y Barba",
                            Precio = 25000m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Cejas Hombre",
                            Precio = 3000m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Barba",
                            Precio = 8000m
                        });
                });

            modelBuilder.Entity("BarberiaTurnos.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BarberoId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric");

                    b.Property<int>("TurnoDiario")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BarberoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("BarberiaTurnos.Models.TurnoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PrecioCobrado")
                        .HasColumnType("numeric");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId");

                    b.HasIndex("TurnoId");

                    b.ToTable("TurnoDetalles");
                });

            modelBuilder.Entity("BarberiaTurnos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Admin",
                            Pin = "0000",
                            Rol = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Barbero 1",
                            Pin = "1111",
                            Rol = "Barbero"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Barbero 2",
                            Pin = "2222",
                            Rol = "Barbero"
                        });
                });

            modelBuilder.Entity("BarberiaTurnos.Models.Turno", b =>
                {
                    b.HasOne("BarberiaTurnos.Models.Usuario", "Barbero")
                        .WithMany()
                        .HasForeignKey("BarberoId");

                    b.HasOne("BarberiaTurnos.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbero");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BarberiaTurnos.Models.TurnoDetalle", b =>
                {
                    b.HasOne("BarberiaTurnos.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberiaTurnos.Models.Turno", "Turno")
                        .WithMany("Detalles")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("BarberiaTurnos.Models.Turno", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
